version: '2'

volumes:
  inkledb:
    external: false

services:

  db:
    env_file: .env
    image: postgres
    volumes:
      - inkledb:/opt
      
  app:
    env_file: .env
    build: .
    image: albancrommer/inklewriter:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
  

